# Generated by Django 4.1.7 on 2023-04-20 16:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('title', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('body', ckeditor.fields.RichTextField()),
                ('total_likes', models.IntegerField(default=0)),
                ('feedback', models.IntegerField(blank=True, default=0)),
                ('sourceCode', models.URLField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='project_dislikes', to='account.profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='project_likes', to='account.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('tags', models.ManyToManyField(blank=True, to='base.tag')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('body', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.projects')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
